root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server.exe ./cmd/server/main.go"
  entrypoint = ["./cmd/server/main.go"]
  bin = "./tmp/server.exe"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "migrations"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go"]
  kill_delay = 500

[log]
  time = false

[misc]
  clean_on_exit = true
